[package]
name = "sandbox"
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
egui.workspace = true
egui-dx11-internal.workspace = true
retour.workspace = true
widestring.workspace = true
windows.workspace = true
sandbox-sdk.workspace = true
