format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
hard_tabs = true
hex_literal_case = "Lower"
imports_granularity = "Module"
newline_style = "Unix"
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
