[package]
name = "sandbox-sdk"
authors.workspace = true
edition.workspace = true

[dependencies]
bitflags = "2.5.0"
itertools = "0.13.0"
memchr = "2.7.2"
widestring = "1.1.0"
windows.workspace = true
